### ISSUE TITLE
Error "message" not serialized by Express and not returned

### ISSUE THREAD

**Issue by gambolputty** [kbariotis/throw.js#23]
Hello,

in the example code the error middleware returns the error like this:

```js
res.status(err.statusCode || 500).json(err);
```

Unfortunately `.json()` doesn't serialize the error object returned by throw.js. The returned JSON in this example would be:

```json
{
    "name": "NotFound",
    "statusCode": 404,
    "errorCode": 404
}
```
The "message"-property is missing.

Solution: To return the complete error object (including "message"-property) I use this instead:

```js
res.set({ 'content-type': 'application/json' }).status(err.statusCode || 500).send(JSON.stringify(err, Object.getOwnPropertyNames(err)))
```
[Source](https://stackoverflow.com/a/26199752)

Can this JSON serialization behaviour maybe implemented in throw.js?

Thanks!

**Comment by kbariotis** [comment]
Great spot @gambolputty, yes absolutely that's something that this library should handle. :) Will try and implement soon.

**Comment by kbariotis** [comment]
#24 @gambolputty let me know what you think :) could you test the PR maybe? Thanks

**Comment by gambolputty** [comment]
@kbariotis  Sorry for the late response! I just tested it and it works perfectly, thank you!
