### ISSUE TITLE
2.1.0 name changes are a breaking change over 2.0.0

### ISSUE THREAD

**Issue by mjhm** [kbariotis/throw.js#6]
I'm getting a lot of error messages that look like:
```
throwjs.notFound is not a function
```
😞  
It might be worthwhile reverting for a 2.2.0 release and rerelease the change with a new major version 3.0.0.  Though I'll probably just lock down on 2.0.0 for now.

**Comment by kbariotis** [comment]
You are right! I am so sorry. Reverting now!

**Comment by kbariotis** [comment]
@mjhm thank you for quickly letting me know. I have messed up the history of this projects and the releases as well. I will clean it up at some point and start again with 3.0.0.

Thank you
